- alias: WakeUp Light Bedroom
  id: '1516469487030'
  hide_entity: true
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.wakeup_start_time_lights.state
      }}'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.wakeup
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.wakeup_weekends
        state: 'on'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: script.wakeup_bedroom

- alias: Weekday Morning On
  action:
    service: script.scene_morning
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  id: '1517158114659'
  trigger:
  - at: 05:30
    platform: time

- action:
  - data:
      entity_id:
      - light.tak_1
      - light.tak_2
      - light.tak_3
      - light.hue_vardagsrum
    service: light.turn_off
  - data:
      entity_id:
      - switch.plant_light
      - switch.cupboard_light
    service: switch.turn_off
  alias: Weekday Morning Off
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  id: '1517160306581'
  trigger:
  - event: sunrise
    offset: 01:00:00
    platform: sun
- action:
  - data:
      brightness: 80
      color_temp: 450
      entity_id:
      - light.tak_1
      - light.tak_2
      - light.tak_3
    service: light.turn_on
  alias: Evening Light On
  condition:
  - after: sunset
    after_offset: -01:00:00
    condition: sun
  id: '1517169567056'
  trigger:
  - entity_id: device_tracker.alberts_iphone
    event: enter
    platform: zone
    zone: zone.home
  - entity_id: device_tracker.astrid_sin_iphone
    event: enter
    platform: zone
    zone: zone.home
- action:
  - data:
      entity_id: switch.heater_livingroom
    service: switch.turn_on
  alias: Heating Morning On
  condition: []
  id: '1517551858893'
  trigger:
  - at: 05:00
    platform: time
- action:
  - data:
      entity_id: switch.heater_livingroom
    service: switch.turn_off
  alias: Heating Morning Off
  condition: []
  id: '1517551936701'
  trigger:
  - at: 07:30
    platform: time
- action:
  - data:
      entity_id: switch.heater_livingroom
    service: switch.turn_on
  alias: Heating Evening On
  condition: []
  id: '1517551977011'
  trigger:
  - at: '16:00'
    platform: time
- action:
  - data:
      entity_id: switch.heater_livingroom
    service: switch.turn_off
  alias: Heating Evening Off
  condition: []
  id: '1517552024666'
  trigger:
  - at: '21:30'
    platform: time
