- alias: WakeUp Light Bedroom
  id: '1516469487030'
  hide_entity: true
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.wakeup_start_time_lights.state
      }}'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.wakeup
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.wakeup_weekends
        state: 'on'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: script.wakeup_bedroom
- action:
  - data:
      brightness: 1
      color_temp: 250
      entity_id:
      - light.vardagsrum_tak
      - light.hue_vardagsrum
    service: light.turn_on
  - data:
      entity_id:
      - switch.plant_light
      - switch.cupboard_light
    service: switch.turn_on
  - data:
      brightness: 100
      color_temp: 250
      entity_id:
      - light.vardagsrum_tak
      - light.hue_vardagsrum
      transition: 2700
    service: light.turn_on
  alias: Weekday Morning On
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  id: '1517158114659'
  trigger:
  - at: 05:30
    platform: time
- action:
  - data:
      entity_id:
      - light.vardagsrum_tak
      - light.hue_vardagsrum
    service: light.turn_off
  - data:
      entity_id:
      - switch.plant_light
      - switch.cupboard_light
    service: switch.turn_off
  alias: Weekday Morning Off
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  id: '1517160306581'
  trigger:
  - event: sunrise
    offset: 01:00:00
    platform: sun
