# Wakeup Light
- alias: WakeUp Light Bedroom
  id: '1516469487030'
  hide_entity: true
  trigger:
    platform: template
    value_template: '{{states.sensor.time.state == states.sensor.wakeup_start_time_lights.state}}'
  condition:
    - condition: state
      entity_id: input_boolean.wakeup
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.wakeup_weekends
          state: 'on'
        - condition: time
          weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    service: script.wakeup_bedroom

# Turn lights on on weekday mornings
- alias: Weekday Morning On
  action:
    service: script.scene_morning
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  id: '1517158114659'
  trigger:
  - at: 05:30
    platform: time

# Turn everything off when the last person leaves on weekdays
- action:
  - data:
      entity_id:
      - light.tak_1
      - light.tak_2
      - light.tak_3
      - light.hue_vardagsrum
      - light.hue_sovrum
    service: light.turn_off
  - data:
      entity_id:
      - switch.plant_light
      - switch.cupboard_light
    service: switch.turn_off
  alias: Weekday Morning Off
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  id: '1517160306581'
  trigger:
  - platform: state
    entity_id: group.all_devices
    to: not_home

# Turn the light on when someone comes home
- action:
  - data: {}
    service: script.scene_evening
  alias: Evening Light On
  id: '1517169567056'
  trigger:
  - platform: state
    entity_id: device_tracker.alberts_iphone, device_tracker.astrid_sin_iphone
    from: not_home
    to: 'home'
  condition:
    condition: or
    conditions:
      - condition : state
        entity_id: device_tracker.astrid_sin_iphone
        state: not_home
      - condition : state
        entity_id: device_tracker.alberts_iphone
        state: not_home

# Start heating in the morning
- action:
  - data:
      entity_id: switch.heater_livingroom
    service: switch.turn_on
  alias: Heating Morning On
  condition:
    - condition: state
      entity_id: input_boolean.heating
      state: 'on'
  id: '1517551858893'
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.heating_mortning_start.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"

# Stop heating in the morning
- action:
  - data:
      entity_id: switch.heater_livingroom
    service: switch.turn_off
  alias: Heating Morning Off
  condition:
    - condition: state
      entity_id: input_boolean.heating
      state: 'on'
  id: '1517551936701'
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.heating_mortning_end.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"

# Start heating in the evening
- action:
  - data:
      entity_id: switch.heater_livingroom
    service: switch.turn_on
  alias: Heating Evening On
  condition:
    - condition: state
      entity_id: input_boolean.heating
      state: 'on'
  id: '1517551977011'
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.heating_evening_start.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"

# Stop heating in the evening
- action:
  - data:
      entity_id: switch.heater_livingroom
    service: switch.turn_off
  alias: Heating Evening Off
  condition:
    - condition: state
      entity_id: input_boolean.heating
      state: 'on'
  id: '1517552024666'
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.heating_evening_end.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"

# Gradually change color temperature in the evening
- action:
  - data:
      color_temp: 370
      entity_id:
      - light_tak_1
      - light_tak_2
      - light_tak_3
    service: light.turn_on
  alias: Sunset temperature change 1
  condition: []
  id: '1520144586626'
  trigger:
  - event: sunset
    platform: sun

# Gradually change color temperature in the evening
- action:
  - data:
      color_temp: 457
      entity_id:
      - light_tak_1
      - light_tak_2
      - light_tak_3
    service: light.turn_on
  alias: Sunset temperature change 2
  condition: []
  id: '1520144636923'
  trigger:
  - event: sunset
    offset: '2:00:00'
    platform: sun

# Change wakeup time
- action:
  - data_template:
      entity_id: input_number.wakeup_hour 
      value: '{{trigger["payload_json"]["alarm_time"][0]}}'
    service: input_number.set_value
  - data_template:
      entity_id: input_number.wakeup_minutes 
      value: '{{trigger["payload_json"]["alarm_time"][1]}}'
    service: input_number.set_value
  id: '1520145586600'
  alias: Move Wakeup
  trigger:
    platform: mqtt
    topic: "alarm_clock"

# Disable wakeup
- action:
  - data:
      entity_id: input_boolean.wakeup
    service: input_boolean.turn_off
  id: '1520145586601'
  alias: Disable Wakeup
  condition:
    - condition: state
      entity_id: input_boolean.wakeup
      state: 'on'
    - condition: template
      value_template: '{{ trigger["payload_json"]["alarm_is_enabled"] == false }}'
  trigger:
    platform: mqtt
    topic: "alarm_clock"

# Enable wakeup
- action:
  - data:
      entity_id: input_boolean.wakeup
    service: input_boolean.turn_on
  id: '1520145586602'
  alias: Enable Wakeup
  condition:
    - condition: state
      entity_id: input_boolean.wakeup
      state: 'off'
    - condition: template
      value_template: '{{ trigger["payload_json"]["alarm_is_enabled"] == true }}'
  trigger:
    platform: mqtt
    topic: "alarm_clock"

# Move alarm
# - action:
#   - data_template:
#       topic: alarm_clock/command
#       payload: '{"command":"toggle_alarm"}'
#       retain: false
#     service: mqtt.publish
#   id: '1520145586603'
#   alias: Move Alarm
#   trigger:
#     platform: state
#     entity_id: input_boolean.wakeup

# Start coffee maker
- action:
  - data:
      entity_id: switch.coffee_maker_new
    service: switch.turn_on
  alias: Start Coffee Maker
  condition:
    - condition: state
      entity_id: input_boolean.coffee_automation
      state: 'on'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  id: '1520145586604'
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.coffee_on_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
