homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - philips_hue
  enable:
    - homekit

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor: !include sensor.yaml

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include_dir_named groups
#automation: !include automations.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml

# Inputs
input_number: !include input/input_number.yaml
input_boolean: !include input/input_boolean.yaml
input_datetime: !include input/input_datetime.yaml

# Apple TV
apple_tv: !include apple_tv.yaml

# Tellstick
tellstick:
  host: core-tellstick
  port: [50800, 50801]

# Zones
zone: !include zone.yaml

# Device tracker
device_tracker: !include device_tracker.yaml

# HomeKit
homekit: !include homekit.yaml

# iOS
ios:

# MQTT
mqtt:
  broker: localhost

# History and retention
recorder: !include recorder.yaml

# Flux settings
switch: !include switch.yaml

# Notofications
notify: !include notify.yaml
