- platform: yr
  name: Weather
  forecast: 2
  monitored_conditions:
    - temperature
    - symbol
- platform: time_date
  display_options:
    - 'time'
# Wakeup Light
- platform: template
  sensors:
    wakeup_alarm_time:
      friendly_name: 'Alarm time'
      value_template: '{% if states.input_number.wakeup_hour.state|length == 3 %}0{% endif %}{{ states.input_number.wakeup_hour.state | int }}:{% if states.input_number.wakeup_minutes.state|length == 3 %}0{% endif %}{{ states.input_number.wakeup_minutes.state | int }}'
- platform: template
  sensors:
    wakeup_start_time_lights:
      friendly_name: 'Fade-in start time'
      value_template: >
        {% if states.sensor.wakeup_alarm_time and states.input_number.wakeup_duration %}
        {% set alarmtime = states.sensor.wakeup_alarm_time.state %}
        {% set alarm_hour = alarmtime.split(":")[0] | int %}
        {% set alarm_min = alarmtime.split(":")[1] | int %}
        {% set light_dur = states.input_number.wakeup_duration.state | int %}
        {% set alarm_min_light = alarm_min - light_dur %}
        {% if alarm_min_light  < 0 %}
        {% set alarm_min_light = alarm_min_light + 60 %}
        {% set alarm_hour_light = alarm_hour - 1 %}
        {% if alarm_hour_light < 0 %}{% set alarm_hour_light = 23 %}{% endif %}
        {% if alarm_hour_light < 10 %}0{% endif %}{{ alarm_hour_light}}:{% if alarm_min_light < 10 %}0{% endif %}{{ alarm_min_light }}
        {% else %}
        {% if alarm_hour < 10 %}0{% endif %}{{ alarm_hour }}:{% if alarm_min_light < 10 %}0{% endif %}{{ alarm_min_light }}
        {% endif %}
        {% endif %}
- platform: template
  sensors:
    wakeup_fadein_duration:
      friendly_name: 'Fade-in duration'
      value_template: '{{ states.input_number.wakeup_duration.state | int }}'
      unit_of_measurement: 'min'

# Plant watering
- platform: template
  sensors:
    plants_need_water:
      friendly_name: 'Group 1 Needs Water'
      icon_template: mdi:water_outline
      value_template: >
        {% if((states.sensor.plant_moisture_1.state|float >= states.input_number.plant_moisture_threshold_1.state|float) or
              (states.sensor.plant_moisture_2.state|float >= states.input_number.plant_moisture_threshold_2.state|float) or
              (states.sensor.plant_moisture_3.state|float >= states.input_number.plant_moisture_threshold_3.state|float) or
              (states.sensor.plant_moisture_4.state|float >= states.input_number.plant_moisture_threshold_4.state|float) or
              (states.sensor.plant_moisture_5.state|float >= states.input_number.plant_moisture_threshold_5.state|float) or
              (states.sensor.plant_moisture_6.state|float >= states.input_number.plant_moisture_threshold_6.state|float)) %}
          {{ 1 }}
        {% else %}
          {{ 0 }}
        {% endif %}

    plants_need_water_2:
      friendly_name: 'Group 2 Needs Water'
      icon_template: mdi:water_outline
      value_template: >
        {% if((states.sensor.plant_moisture_7.state|float >= states.input_number.plant_moisture_threshold_7.state|float) or
              (states.sensor.plant_moisture_8.state|float >= states.input_number.plant_moisture_threshold_8.state|float) or
              (states.sensor.plant_moisture_9.state|float >= states.input_number.plant_moisture_threshold_9.state|float) or
              (states.sensor.plant_moisture_10.state|float >= states.input_number.plant_moisture_threshold_10.state|float) or
              (states.sensor.plant_moisture_11.state|float >= states.input_number.plant_moisture_threshold_11.state|float) or
              (states.sensor.plant_moisture_12.state|float >= states.input_number.plant_moisture_threshold_12.state|float)) %}
          {{ 1 }}
        {% else %}
          {{ 0 }}
        {% endif %}
