title: Home
resources:
  - url: /local/state-history-card/state-history-card.js
    type: js

views:
  # Main tab
  - title: Home 
    path: home
    cards:
      - id: modes
        type: entities
        title: Modes
        entities: 
          - script.scene_daytime
          - script.scene_evening
          - script.scene_night
      - id: weather
        type: weather-forecast
        entity: weather.weather
      - id: livingroom-temperature-gauge
        name: Livingroom
        type: gauge
        unit: °C
        min: -30
        max: 40
        severity:
          green: 18
          yellow: 25
          red: 30
        entity: sensor.livingroom_temperature
      - id: outdoor-temperature-gauge
        name: Outdoor
        type: gauge
        unit: °C
        min: -30
        max: 40
        severity:
          green: 18
          yellow: 25
          red: 30
        entity: sensor.outdoor_temperature
      - id: people
        type: entities
        entities:
          - device_tracker.astrid_sin_iphone
          - device_tracker.alberts_phone
        card:
          type: glance
      - id: map
        type: map
        aspect_ratio: 80%
        entities:
          - device_tracker.astrid_sin_iphone
          - device_tracker.alberts_phone
          - zone.home
          - zone.mogi
          - zone.acando
  # Light tab
  - title: Light
    path: light
    cards:
      - id: livingroom
        title: Livingroom
        type: entities
        entities:
          - group.light_livingroom_ceiling
          - light.tak_1
          - light.tak_2
          - light.tak_3
          - light.hue_vardagsrum
          - switch.cupboard_light
          - switch.tv_light_new
          - switch.sofa_light
          - switch.plant_light
      - id: bedroom
        title: Bedroom
        type: entities
        entities:
          - light.hue_sovrum
          - light.bed_lamp
      - id: circadian
        title: Automatic Light Control
        type: entities
        show_header_toggle: false
        entities:
          - input_boolean.auto_sunset
      - id: entrance
        title: Entrance
        type: entities
        entities:
          - switch.hallway_ceiling_light
          - switch.hallway_wall_light
      - id: wakup-light
        title: Wakeup Light
        show_header_toggle: false
        type: entities
        entities:
          - sensor.wakeup_alarm_time
          - sensor.wakeup_start_time_lights
          - sensor.wakeup_fadein_duration
          - input_number.wakeup_hour
          - input_number.wakeup_minutes
          - input_number.wakeup_duration
          - input_boolean.wakeup
          - input_boolean.wakeup_weekends

  # Coffee tab
  - title: Coffee
    path: coffee
    cards:
      - id: coffee-switch
        type: entities
        entities:
          - switch.coffee_maker_2
      - id: coffee-automation
        type: entities
        title: Automation
        show_header_toggle: false
        entities:
          - input_boolean.coffee_automation
          - input_datetime.coffee_on_time
          - input_number.coffee_on_duration
          - script.coffee_auto_off
          - script.coffee_trigger

  # Heating tab
  - title: Heating
    path: heating
    cards:
      - id: heating-switch
        type: entities
        entities:
          - switch.heater_livingroom
      - id: heating-automation
        type: entities
        title: Automation
        show_header_toggle: false
        entities:
          - input_boolean.heating
          - input_datetime.heating_mortning_start
          - input_datetime.heating_mortning_end
          - input_datetime.heating_evening_start
          - input_datetime.heating_evening_end
  
  # Plants tab
  - title: Plants
    path: plants
    cards:
      - id: plant-moisture-gauge
        type: gauge
        unit: V
        min: 1.6
        max: 3.3
        severity:
          green: 2
          yellow: 2.5
          red: 3
        entity: sensor.plant_moisture
      - id: plant-moisture-history
        type: history-graph
        hours_to_show: 80
        entities:
          - sensor.plant_moisture

  # Location tab.
  - title: Location
    path: location
    cards:
      - type: "custom:state-history-card"
        entity: device_tracker.alberts_phone
      - type: "custom:state-history-card"
        entity: device_tracker.astrid_sin_iphone

  # Control tab
  - title: Control
    path: control
    cards:
      - id: control-scripts
        type: entities
        show_header_toggle: false
        entities:
          - type: call-service
            name: Restart HA
            service: homeassistant.restart
          - type: call-service
            name: Reload Core
            service: homeassistant.reload_core_config
          - type: call-service
            name: Reload Groups
            service: group.reload
          - type: call-service
            name: Reload Automations
            service: automation.reload
          - type: call-service
            name: Reload Scripts
            service: script.reload
          - type: call-service
            service: frontend.reload_themes
            name: Reload Themes