title: Home
background: var(--background-image)
resources:
  - url: /local/state-history-card/state-history-card.js
    type: js
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module

cch:
  background: rgba(155, 155, 155, 0.25)
  clock_format: 24
  swipe_animate: fade
  swipe_prevent_default: true

views:
  # Main tab
  - title: Home 
    path: home
    cards:
      - id: modes
        type: entities
        title: Modes
        entities: 
          - script.scene_daytime
          - script.scene_evening
          - script.scene_night
      - id: weather
        type: weather-forecast
        entity: weather.weather
      - id: livingroom-temperature-gauge
        name: Livingroom
        type: gauge
        unit: °C
        min: -30
        max: 40
        severity:
          green: 18
          yellow: 25
          red: 30
        entity: sensor.livingroom_temperature
      - id: outdoor-temperature-gauge
        name: Outdoor
        type: gauge
        unit: °C
        min: -30
        max: 40
        severity:
          green: 18
          yellow: 25
          red: 30
        entity: sensor.outdoor_temperature
      - id: people
        type: entities
        entities:
          - device_tracker.astrid_sin_iphone_2
          - device_tracker.alberts_iphone
        card:
          type: glance
      - id: map
        type: map
        aspect_ratio: 80%
        entities:
          - device_tracker.astrid_sin_iphone_2
          - device_tracker.alberts_iphone
          - zone.home
          - zone.mogi
          - zone.acando
          - zone.airthings
          - zone.sats_carl_berner
  # Light tab
  - title: Light
    path: light
    cards:
      - id: livingroom
        title: Livingroom
        type: entities
        entities:
          - group.light_livingroom_ceiling
          - light.tak_1
          - light.tak_2
          - light.tak_3
          - light.hue_vardagsrum
          - switch.cupboard_light
          - switch.tv_light_new
          - switch.sofa_light
          - switch.plant_light
      - id: bedroom
        title: Bedroom
        type: entities
        entities:
          - light.hue_sovrum
          - light.bed_lamp
      - id: light-automation
        title: Automatic Light Control
        type: entities
        show_header_toggle: false
        entities:
          - input_boolean.presence_lighting
          - input_boolean.auto_sunset
      - id: entrance
        title: Entrance
        type: entities
        entities:
          - switch.hallway_ceiling_light
          - switch.hallway_wall_light
      - id: wakup-light
        title: Wakeup Light
        show_header_toggle: false
        type: entities
        entities:
          - sensor.wakeup_alarm_time
          - sensor.wakeup_start_time_lights
          - sensor.wakeup_fadein_duration
          - input_number.wakeup_hour
          - input_number.wakeup_minutes
          - input_number.wakeup_duration
          - input_boolean.wakeup
          - input_boolean.wakeup_weekends

  # Coffee tab
  - title: Coffee
    path: coffee
    cards:
      - id: coffee-switch
        type: entities
        entities:
          - switch.coffee_maker_2
      - id: coffee-automation
        type: entities
        title: Automation
        show_header_toggle: false
        entities:
          - input_boolean.coffee_automation
          - input_datetime.coffee_on_time
          - input_number.coffee_on_duration
          - script.coffee_auto_off
          - script.coffee_trigger

  # Heating tab
  - title: Heating
    path: heating
    cards:
      - id: heating-switch
        type: entities
        entities:
          - switch.heater_livingroom
      - id: heating-automation
        type: entities
        title: Automation
        show_header_toggle: false
        entities:
          - input_boolean.heating
          - input_datetime.heating_mortning_start
          - input_datetime.heating_mortning_end
          - input_datetime.heating_evening_start
          - input_datetime.heating_evening_end
  
  # Plants tab
  - title: Plants
    path: plants
    cards:
      - id: group-1
        type: vertical-stack
        cards:
        - id: plant-status
          type: entities
          entities:
            - switch.water_pump_1
            - entity: sensor.plants_need_water
              icon: mdi:cactus
        - id: plant-moisture-history
          type: history-graph
          hours_to_show: 80
          entities:
            - sensor.plant_moisture_1
            - sensor.plant_moisture_2
            - sensor.plant_moisture_3
            - sensor.plant_moisture_4
            - sensor.plant_moisture_5
            - switch.water_pump_1
            - sensor.plants_need_water
        - id: plant-1
          type: vertical-stack
          cards:
            - id: plant-moisture-gauge-1
              name: Aloe Vera
              type: gauge
              unit: V
              min: 1.6
              max: 3.3
              severity:
                green: 2
                yellow: 2.5
                red: 3
              entity: sensor.plant_moisture_1
            - type: entities
              entities:
                - entity: input_number.plant_moisture_threshold_1
                  name: Threshold
                  icon: mdi:chart-line
        - id: plant-2
          type: vertical-stack
          cards:
            - id: plant-moisture-gauge-2
              name: Elefantöra
              type: gauge
              unit: V
              min: 1.6
              max: 3.3
              severity:
                green: 2
                yellow: 2.5
                red: 3
              entity: sensor.plant_moisture_2
            - type: entities
              entities:
                - entity: input_number.plant_moisture_threshold_2
                  name: Threshold
                  icon: mdi:chart-line
        - id: plant-3
          type: vertical-stack
          cards:
            - id: plant-moisture-gauge-3
              name: Orkidé
              type: gauge
              unit: V
              min: 1.6
              max: 3.3
              severity:
                green: 2
                yellow: 2.5
                red: 3
              entity: sensor.plant_moisture_3
            - type: entities
              entities:
                - entity: input_number.plant_moisture_threshold_3
                  name: Threshold
                  icon: mdi:chart-line
        - id: plant-4
          type: vertical-stack
          cards:
            - id: plant-moisture-gauge-4
              name: Suckulent
              type: gauge
              unit: V
              min: 1.6
              max: 3.3
              severity:
                green: 2
                yellow: 2.5
                red: 3
              entity: sensor.plant_moisture_4
            - type: entities
              entities:
                - entity: input_number.plant_moisture_threshold_4
                  name: Threshold
                  icon: mdi:chart-line
        - id: plant-5
          type: vertical-stack
          cards:
            - id: plant-moisture-gauge-5
              name: Paradisträd
              type: gauge
              unit: V
              min: 1.6
              max: 3.3
              severity:
                green: 2
                yellow: 2.5
                red: 3
              entity: sensor.plant_moisture_5
            - type: entities
              entities:
                - entity: input_number.plant_moisture_threshold_5
                  name: Threshold
                  icon: mdi:chart-line

      # Group 2
      - id: group-2
        type: vertical-stack
        cards:
        - id: plant-status-2
          type: entities
          entities:
            - switch.water_pump_2
            - entity: sensor.plants_need_water_2
              icon: mdi:cactus
        - id: plant-moisture-history-2
          type: history-graph
          hours_to_show: 80
          entities:
            - sensor.plant_moisture_7
            - sensor.plant_moisture_8
            - sensor.plant_moisture_9
            - sensor.plant_moisture_10
            - sensor.plant_moisture_11
            - switch.water_pump_2
            - sensor.plants_need_water_2
        - id: plant-7
          type: vertical-stack
          cards:
            - id: plant-moisture-gauge-7
              name: Sprättiväg
              type: gauge
              unit: V
              min: 1.6
              max: 3.3
              severity:
                green: 2
                yellow: 2.5
                red: 3
              entity: sensor.plant_moisture_7
            - type: entities
              entities:
                - entity: input_number.plant_moisture_threshold_7
                  name: Threshold
                  icon: mdi:chart-line
        - id: plant-8
          type: vertical-stack
          cards:
            - id: plant-moisture-gauge-8
              name: Avocado mini
              type: gauge
              unit: V
              min: 1.6
              max: 3.3
              severity:
                green: 2
                yellow: 2.5
                red: 3
              entity: sensor.plant_moisture_8
            - type: entities
              entities:
                - entity: input_number.plant_moisture_threshold_8
                  name: Threshold
                  icon: mdi:chart-line
        - id: plant-9
          type: vertical-stack
          cards:
            - id: plant-moisture-gauge-9
              name: Chili
              type: gauge
              unit: V
              min: 1.6
              max: 3.3
              severity:
                green: 2
                yellow: 2.5
                red: 3
              entity: sensor.plant_moisture_9
            - type: entities
              entities:
                - entity: input_number.plant_moisture_threshold_9
                  name: Threshold
                  icon: mdi:chart-line
        - id: plant-10
          type: vertical-stack
          cards:
            - id: plant-moisture-gauge-10
              name: Avocado
              type: gauge
              unit: V
              min: 1.6
              max: 3.3
              severity:
                green: 2
                yellow: 2.5
                red: 3
              entity: sensor.plant_moisture_10
            - type: entities
              entities:
                - entity: input_number.plant_moisture_threshold_10
                  name: Threshold
                  icon: mdi:chart-line
        - id: plant-11
          type: vertical-stack
          cards:
            - id: plant-moisture-gauge-11
              name: Aloe Vera stor
              type: gauge
              unit: V
              min: 1.6
              max: 3.3
              severity:
                green: 2
                yellow: 2.5
                red: 3
              entity: sensor.plant_moisture_11
            - type: entities
              entities:
                - entity: input_number.plant_moisture_threshold_11
                  name: Threshold
                  icon: mdi:chart-line

  # Location tab.
  - title: Location
    path: location
    cards:
      - type: "custom:state-history-card"
        entity: device_tracker.alberts_iphone
      - type: "custom:state-history-card"
        entity: device_tracker.astrid_sin_iphone_2

  # Control tab
  - title: Control
    path: control
    cards:
      - id: control-scripts
        type: entities
        show_header_toggle: false
        entities:
          - type: call-service
            name: Restart HA
            service: homeassistant.restart
          - type: call-service
            name: Reload Core
            service: homeassistant.reload_core_config
          - type: call-service
            name: Reload Groups
            service: group.reload
          - type: call-service
            name: Reload Automations
            service: automation.reload
          - type: call-service
            name: Reload Scripts
            service: script.reload
          - type: call-service
            service: frontend.reload_themes
            name: Reload Themes