# Automatic Sunset
- alias: Automatic Sunset 1
  hide_entity: true
  trigger:
    platform: time
    at: '16:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.auto_sunset
      state: 'on'
    - condition: state
      entity_id: group.light_livingroom_ceiling
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.tak_1
          - light.tak_2
          - light.tak_3
          - light.hue_vardagsrum
        brightness_pct: 50
        transition: 900

- alias: Automatic Sunset 2
  hide_entity: true
  trigger:
    platform: time
    at: '16:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.auto_sunset
      state: 'on'
    - condition: state
      entity_id: group.light_livingroom_ceiling
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.tak_1
          - light.tak_2
          - light.tak_3
          - light.hue_vardagsrum
        color_temp: 454
        transition: 900

- alias: Automatic Sunset 3
  hide_entity: true
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.auto_sunset
      state: 'on'
    - condition: state
      entity_id: group.light_livingroom_ceiling
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.tak_1
          - light.tak_2
          - light.tak_3
          #- light.hue_vardagsrum
        brightness_pct: 1
        transition: 900
