# Turn everything off when the last person leaves on weekdays
- alias: Weekday Morning Off
  action:
    - data:
        entity_id:
          - light.tak_1
          - light.tak_2
          - light.tak_3
          - light.hue_vardagsrum
          - light.hue_sovrum
      service: light.turn_off
    - data:
        entity_id:
          - switch.plant_light
          - switch.cupboard_light
      service: switch.turn_off
  trigger:
    - platform: state
      entity_id: group.all_devices
      from: 'home'
      to: not_home
  condition:
    - condition: template
      value_template: >-
        {{
          not (is_state('device_tracker.alberts_phone', 'home')
           or is_state('device_tracker.astrid_sin_iphone', 'home'))
        }}

# Turn the light on when someone comes home
- alias: Evening Light On
  action:
    - service: script.scene_evening
  trigger:
    - platform: state
      entity_id: device_tracker.alberts_phone, device_tracker.astrid_sin_iphone
      from: not_home
      to: 'home'
  condition:
    - condition: template
      value_template: >-
        {{
          not (is_state('device_tracker.alberts_phone', 'home')
           and is_state('device_tracker.astrid_sin_iphone', 'home'))
        }}
