# Wakeup Light
- alias: WakeUp Light Bedroom
  hide_entity: true
  trigger:
    platform: template
    value_template: '{{states.sensor.time.state == states.sensor.wakeup_start_time_lights.state}}'
  condition:
    - condition: state
      entity_id: input_boolean.wakeup
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.wakeup_weekends
          state: 'on'
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
  action:
    - service: script.wakeup_bedroom
    - service: script.scene_morning

# Change wakeup time
- alias: Move Wakeup
  action:
    - data_template:
        entity_id: input_number.wakeup_hour
        value: '{{trigger["payload_json"]["alarm_time"][0]}}'
      service: input_number.set_value
    - data_template:
        entity_id: input_number.wakeup_minutes
        value: '{{trigger["payload_json"]["alarm_time"][1]}}'
      service: input_number.set_value
  trigger:
    platform: mqtt
    topic: "alarm_clock"

# Disable wakeup
- alias: Disable Wakeup
  action:
    - data:
        entity_id: input_boolean.wakeup
      service: input_boolean.turn_off
  condition:
    - condition: state
      entity_id: input_boolean.wakeup
      state: 'on'
    - condition: template
      value_template: '{{ trigger["payload_json"]["alarm_is_enabled"] == false }}'
  trigger:
    platform: mqtt
    topic: "alarm_clock"

# Enable wakeup
- alias: Enable Wakeup
  action:
    - data:
        entity_id: input_boolean.wakeup
      service: input_boolean.turn_on
  condition:
    - condition: state
      entity_id: input_boolean.wakeup
      state: 'off'
    - condition: template
      value_template: '{{ trigger["payload_json"]["alarm_is_enabled"] == true }}'
  trigger:
    platform: mqtt
    topic: "alarm_clock"

# Move alarm
# - action:
#   - data_template:
#       topic: alarm_clock/command
#       payload: '{"command":"toggle_alarm"}'
#       retain: false
#     service: mqtt.publish
#   alias: Move Alarm
#   trigger:
#     platform: state
#     entity_id: input_boolean.wakeup
